/*
 * Generated by XDoclet - Do not edit!
 */
package com.duroty.application.mail.interfaces;

/**
 * Home interface for Send.
 * @xdoclet-generated at ${TODAY}
 * @copyright The XDoclet Team
 * @author XDoclet
 * @version ${version}
 */
public interface SendHome
   extends javax.ejb.EJBHome
{
   public static final String COMP_NAME="duroty/ejb/Send";
   public static final String JNDI_NAME="duroty/ejb/Send";

   public com.duroty.application.mail.interfaces.Send create()
      throws javax.ejb.CreateException,java.rmi.RemoteException;

}
