/*
 * Generated by XDoclet - Do not edit!
 */
package com.duroty.application.home.interfaces;

/**
 * Home interface for Home.
 * @xdoclet-generated at ${TODAY}
 * @copyright The XDoclet Team
 * @author XDoclet
 * @version ${version}
 */
public interface HomeHome
   extends javax.ejb.EJBHome
{
   public static final String COMP_NAME="duroty/ejb/Home";
   public static final String JNDI_NAME="duroty/ejb/Home";

   public com.duroty.application.home.interfaces.Home create()
      throws javax.ejb.CreateException,java.rmi.RemoteException;

}
