/*
 * Generated by XDoclet - Do not edit!
 */
package com.duroty.application.bookmark.interfaces;

/**
 * Home interface for Bookmark.
 * @xdoclet-generated at ${TODAY}
 * @copyright The XDoclet Team
 * @author XDoclet
 * @version ${version}
 */
public interface BookmarkHome
   extends javax.ejb.EJBHome
{
   public static final String COMP_NAME="duroty/ejb/Bookmark";
   public static final String JNDI_NAME="duroty/ejb/Bookmark";

   public com.duroty.application.bookmark.interfaces.Bookmark create()
      throws javax.ejb.CreateException,java.rmi.RemoteException;

}
