package com.duroty.hibernate;


// Generated 17-oct-2006 10:28:11 by Hibernate Tools 3.1.0.beta5

/**
 * BayesianSpam generated by hbm2java
 */
public class BayesianSpam implements java.io.Serializable {
    // Fields    

    /**
     *
     */
    private static final long serialVersionUID = -4559530036321496415L;

    /**
     * DOCUMENT ME!
     */
    private int spamIdint;

    /**
     * DOCUMENT ME!
     */
    private Users users;

    /**
     * DOCUMENT ME!
     */
    private String spamToken;

    /**
     * DOCUMENT ME!
     */
    private int spamOcurrences;

    // Constructors

    /** default constructor */
    public BayesianSpam() {
    }

    /** full constructor */
    public BayesianSpam(int spamIdint, Users users, String spamToken,
        int spamOcurrences) {
        this.spamIdint = spamIdint;
        this.users = users;
        this.spamToken = spamToken;
        this.spamOcurrences = spamOcurrences;
    }

    // Property accessors
    public int getSpamIdint() {
        return this.spamIdint;
    }

    /**
     * DOCUMENT ME!
     *
     * @param spamIdint DOCUMENT ME!
     */
    public void setSpamIdint(int spamIdint) {
        this.spamIdint = spamIdint;
    }

    /**
     * DOCUMENT ME!
     *
     * @return DOCUMENT ME!
     */
    public Users getUsers() {
        return this.users;
    }

    /**
     * DOCUMENT ME!
     *
     * @param users DOCUMENT ME!
     */
    public void setUsers(Users users) {
        this.users = users;
    }

    /**
     * DOCUMENT ME!
     *
     * @return DOCUMENT ME!
     */
    public String getSpamToken() {
        return this.spamToken;
    }

    /**
     * DOCUMENT ME!
     *
     * @param spamToken DOCUMENT ME!
     */
    public void setSpamToken(String spamToken) {
        this.spamToken = spamToken;
    }

    /**
     * DOCUMENT ME!
     *
     * @return DOCUMENT ME!
     */
    public int getSpamOcurrences() {
        return this.spamOcurrences;
    }

    /**
     * DOCUMENT ME!
     *
     * @param spamOcurrences DOCUMENT ME!
     */
    public void setSpamOcurrences(int spamOcurrences) {
        this.spamOcurrences = spamOcurrences;
    }
}
