package com.duroty.hibernate;


// Generated 14-sep-2006 11:28:32 by Hibernate Tools 3.1.0.beta5

/**
 * ConColi generated by hbm2java
 */
public class ConColi implements java.io.Serializable {
    // Fields    

    /**
         *
         */
    private static final long serialVersionUID = 8636739305521450310L;

    /**
    * DOCUMENT ME!
    */
    private ConColiId id;

    // Constructors

    /** default constructor */
    public ConColi() {
    }

    /** full constructor */
    public ConColi(ConColiId id) {
        this.id = id;
    }

    // Property accessors
    public ConColiId getId() {
        return this.id;
    }

    /**
     * DOCUMENT ME!
     *
     * @param id DOCUMENT ME!
     */
    public void setId(ConColiId id) {
        this.id = id;
    }
}
