package com.duroty.hibernate;


// Generated 31-jul-2006 11:12:15 by Hibernate Tools 3.1.0.beta5
import java.util.HashSet;
import java.util.Set;


/**
 * FeedChannel generated by hbm2java
 */
public class FeedChannel implements java.io.Serializable {
    // Fields    

    /**
     *
     */
    private static final long serialVersionUID = 1569270458706357680L;

    /**
     * DOCUMENT ME!
     */
    private int fechIdint;

    /**
     * DOCUMENT ME!
     */
    private Users users;

    /**
     * DOCUMENT ME!
     */
    private String fechName;

    /**
     * DOCUMENT ME!
     */
    private Set feedDatas = new HashSet(0);

    // Constructors

    /** default constructor */
    public FeedChannel() {
    }

    /** minimal constructor */
    public FeedChannel(int fechIdint, Users users, String fechName) {
        this.fechIdint = fechIdint;
        this.users = users;
        this.fechName = fechName;
    }

    /** full constructor */
    public FeedChannel(int fechIdint, Users users, String fechName,
        Set feedDatas) {
        this.fechIdint = fechIdint;
        this.users = users;
        this.fechName = fechName;
        this.feedDatas = feedDatas;
    }

    // Property accessors
    /**
     * DOCUMENT ME!
     *
     * @return DOCUMENT ME!
     */
    public int getFechIdint() {
        return this.fechIdint;
    }

    /**
     * DOCUMENT ME!
     *
     * @param fechIdint DOCUMENT ME!
     */
    public void setFechIdint(int fechIdint) {
        this.fechIdint = fechIdint;
    }

    /**
     * DOCUMENT ME!
     *
     * @return DOCUMENT ME!
     */
    public Users getUsers() {
        return this.users;
    }

    /**
     * DOCUMENT ME!
     *
     * @param users DOCUMENT ME!
     */
    public void setUsers(Users users) {
        this.users = users;
    }

    /**
     * DOCUMENT ME!
     *
     * @return DOCUMENT ME!
     */
    public String getFechName() {
        return this.fechName;
    }

    /**
     * DOCUMENT ME!
     *
     * @param fechName DOCUMENT ME!
     */
    public void setFechName(String fechName) {
        this.fechName = fechName;
    }

    /**
     * DOCUMENT ME!
     *
     * @return DOCUMENT ME!
     */
    public Set getFeedDatas() {
        return this.feedDatas;
    }

    /**
     * DOCUMENT ME!
     *
     * @param feedDatas DOCUMENT ME!
     */
    public void setFeedDatas(Set feedDatas) {
        this.feedDatas = feedDatas;
    }
}
