/*
* Copyright (C) 2006 Jordi Marquès Ferré
*
* This program is free software; you can redistribute it and/or modify
* it under the terms of the GNU General Public License as published by
* the Free Software Foundation; either version 2 of the License, or
* (at your option) any later version.
*
* This program is distributed in the hope that it will be useful,
* but WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
* GNU General Public License for more details.
*
* You should have received a copy of the GNU General Public License
* along with this software; see the file DUROTY.txt.
*
* Author: Jordi Marquès Ferré
* c/Mallorca 295 principal B 08037 Barcelona Spain
* Phone: +34 625397324
*/


package com.duroty.hibernate;


// Generated 02-ago-2006 17:07:31 by Hibernate Tools 3.1.0.beta5

/**
 * Filter generated by hbm2java
 */
public class Filter implements java.io.Serializable {
    // Fields    

    /**
         *
         */
    private static final long serialVersionUID = 2581505238861573250L;

    /**
    * DOCUMENT ME!
    */
    private int filIdint;

    /**
     * DOCUMENT ME!
     */
    private Label label;

    /**
     * DOCUMENT ME!
     */
    private String filFrom;

    /**
     * DOCUMENT ME!
     */
    private String filTo;

    /**
     * DOCUMENT ME!
     */
    private String filSubject;

    /**
     * DOCUMENT ME!
     */
    private String filHasWords;

    /**
     * DOCUMENT ME!
     */
    private String filDoesntHaveWords;

    /**
     * DOCUMENT ME!
     */
    private boolean filHasAttacment;

    /**
     * DOCUMENT ME!
     */
    private boolean filArchive;

    /**
     * DOCUMENT ME!
     */
    private boolean filImportant;

    /**
     * DOCUMENT ME!
     */
    private boolean filTrash;

    /**
     * DOCUMENT ME!
     */
    private String filForwardTo;

    /**
     * DOCUMENT ME!
     */
    private boolean filOrOperator;

    // Constructors

    /** default constructor */
    public Filter() {
    }

    /** minimal constructor */
    public Filter(int filIdint, Label label, boolean filHasAttacment,
        boolean filArchive, boolean filImportant, boolean filTrash,
        boolean filOrOperator) {
        this.filIdint = filIdint;
        this.label = label;
        this.filHasAttacment = filHasAttacment;
        this.filArchive = filArchive;
        this.filImportant = filImportant;
        this.filTrash = filTrash;
        this.filOrOperator = filOrOperator;
    }

    /** full constructor */
    public Filter(int filIdint, Label label, String filFrom, String filTo,
        String filSubject, String filHasWords, String filDoesntHaveWords,
        boolean filHasAttacment, boolean filArchive, boolean filImportant,
        boolean filTrash, String filForwardTo, boolean filOrOperator) {
        this.filIdint = filIdint;
        this.label = label;
        this.filFrom = filFrom;
        this.filTo = filTo;
        this.filSubject = filSubject;
        this.filHasWords = filHasWords;
        this.filDoesntHaveWords = filDoesntHaveWords;
        this.filHasAttacment = filHasAttacment;
        this.filArchive = filArchive;
        this.filImportant = filImportant;
        this.filTrash = filTrash;
        this.filForwardTo = filForwardTo;
        this.filOrOperator = filOrOperator;
    }

    // Property accessors
    public int getFilIdint() {
        return this.filIdint;
    }

    /**
     * DOCUMENT ME!
     *
     * @param filIdint DOCUMENT ME!
     */
    public void setFilIdint(int filIdint) {
        this.filIdint = filIdint;
    }

    /**
     * DOCUMENT ME!
     *
     * @return DOCUMENT ME!
     */
    public Label getLabel() {
        return this.label;
    }

    /**
     * DOCUMENT ME!
     *
     * @param label DOCUMENT ME!
     */
    public void setLabel(Label label) {
        this.label = label;
    }

    /**
     * DOCUMENT ME!
     *
     * @return DOCUMENT ME!
     */
    public String getFilFrom() {
        return this.filFrom;
    }

    /**
     * DOCUMENT ME!
     *
     * @param filFrom DOCUMENT ME!
     */
    public void setFilFrom(String filFrom) {
        this.filFrom = filFrom;
    }

    /**
     * DOCUMENT ME!
     *
     * @return DOCUMENT ME!
     */
    public String getFilTo() {
        return this.filTo;
    }

    /**
     * DOCUMENT ME!
     *
     * @param filTo DOCUMENT ME!
     */
    public void setFilTo(String filTo) {
        this.filTo = filTo;
    }

    /**
     * DOCUMENT ME!
     *
     * @return DOCUMENT ME!
     */
    public String getFilSubject() {
        return this.filSubject;
    }

    /**
     * DOCUMENT ME!
     *
     * @param filSubject DOCUMENT ME!
     */
    public void setFilSubject(String filSubject) {
        this.filSubject = filSubject;
    }

    /**
     * DOCUMENT ME!
     *
     * @return DOCUMENT ME!
     */
    public String getFilHasWords() {
        return this.filHasWords;
    }

    /**
     * DOCUMENT ME!
     *
     * @param filHasWords DOCUMENT ME!
     */
    public void setFilHasWords(String filHasWords) {
        this.filHasWords = filHasWords;
    }

    /**
     * DOCUMENT ME!
     *
     * @return DOCUMENT ME!
     */
    public String getFilDoesntHaveWords() {
        return this.filDoesntHaveWords;
    }

    /**
     * DOCUMENT ME!
     *
     * @param filDoesntHaveWords DOCUMENT ME!
     */
    public void setFilDoesntHaveWords(String filDoesntHaveWords) {
        this.filDoesntHaveWords = filDoesntHaveWords;
    }

    /**
     * DOCUMENT ME!
     *
     * @return DOCUMENT ME!
     */
    public boolean isFilHasAttacment() {
        return this.filHasAttacment;
    }

    /**
     * DOCUMENT ME!
     *
     * @param filHasAttacment DOCUMENT ME!
     */
    public void setFilHasAttacment(boolean filHasAttacment) {
        this.filHasAttacment = filHasAttacment;
    }

    /**
     * DOCUMENT ME!
     *
     * @return DOCUMENT ME!
     */
    public boolean isFilArchive() {
        return this.filArchive;
    }

    /**
     * DOCUMENT ME!
     *
     * @param filArchive DOCUMENT ME!
     */
    public void setFilArchive(boolean filArchive) {
        this.filArchive = filArchive;
    }

    /**
     * DOCUMENT ME!
     *
     * @return DOCUMENT ME!
     */
    public boolean isFilImportant() {
        return this.filImportant;
    }

    /**
     * DOCUMENT ME!
     *
     * @param filImportant DOCUMENT ME!
     */
    public void setFilImportant(boolean filImportant) {
        this.filImportant = filImportant;
    }

    /**
     * DOCUMENT ME!
     *
     * @return DOCUMENT ME!
     */
    public boolean isFilTrash() {
        return this.filTrash;
    }

    /**
     * DOCUMENT ME!
     *
     * @param filTrash DOCUMENT ME!
     */
    public void setFilTrash(boolean filTrash) {
        this.filTrash = filTrash;
    }

    /**
     * DOCUMENT ME!
     *
     * @return DOCUMENT ME!
     */
    public String getFilForwardTo() {
        return this.filForwardTo;
    }

    /**
     * DOCUMENT ME!
     *
     * @param filForwardTo DOCUMENT ME!
     */
    public void setFilForwardTo(String filForwardTo) {
        this.filForwardTo = filForwardTo;
    }

    /**
     * DOCUMENT ME!
     *
     * @return DOCUMENT ME!
     */
    public boolean isFilOrOperator() {
        return this.filOrOperator;
    }

    /**
     * DOCUMENT ME!
     *
     * @param filOrOperator DOCUMENT ME!
     */
    public void setFilOrOperator(boolean filOrOperator) {
        this.filOrOperator = filOrOperator;
    }
}
