package com.duroty.hibernate;


// Generated 02-ago-2006 17:07:31 by Hibernate Tools 3.1.0.beta5

/**
 * LabMes generated by hbm2java
 */
public class LabMes implements java.io.Serializable {
    // Fields    

    /**
     *
     */
    private static final long serialVersionUID = 874728225161192357L;

    /**
     * DOCUMENT ME!
     */
    private LabMesId id;

    // Constructors

    /** default constructor */
    public LabMes() {
    }

    /** full constructor */
    public LabMes(LabMesId id) {
        this.id = id;
    }

    // Property accessors
    public LabMesId getId() {
        return this.id;
    }

    /**
     * DOCUMENT ME!
     *
     * @param id DOCUMENT ME!
     */
    public void setId(LabMesId id) {
        this.id = id;
    }
}
