/*
 * Generated by XDoclet - Do not edit!
 */
package com.duroty.application.chat.interfaces;

/**
 * Remote interface for Chat.
 * @xdoclet-generated at ${TODAY}
 * @copyright The XDoclet Team
 * @author XDoclet
 * @version ${version}
 */
public interface Chat
   extends javax.ejb.EJBObject
{
   /**
    * //////////// sending a message //////////// // message parts (within array $_POST): // // recipient- user receiving the message// ///////////////////////////////////////////
    * @throws ChatException Thrown if method fails due to system-level error.    */
   public void send( java.lang.String recipient,java.lang.String message,int flag )
      throws com.duroty.application.chat.exceptions.ChatException, java.rmi.RemoteException;

   /**
    * ///////////// ping the server ///////////// // note: since the server cannot contact // // the client, the client must // // ping the server for new msgs // // // // ping parts (within array $_POST): // ///////////////////////////////////////////
    * @throws ChatException Thrown if method fails due to system-level error.    */
   public java.lang.String ping( int away )
      throws com.duroty.application.chat.exceptions.ChatException, java.rmi.RemoteException;

   /**
    * ///////////// login to the server ///////// // login parts (within array $_POST): // // from - user logging in // // pwd - password // ///////////////////////////////////////////
    * @throws ChatException Thrown if method fails due to system-level error.    */
   public void login(  )
      throws com.duroty.application.chat.exceptions.ChatException, java.rmi.RemoteException;

   /**
    * ///////////// login to the server ///////// // login parts (within array $_POST): // // from - user logging in // // pwd - password // ///////////////////////////////////////////
    * @throws ChatException Thrown if method fails due to system-level error.    */
   public void signin(  )
      throws com.duroty.application.chat.exceptions.ChatException, java.rmi.RemoteException;

   /**
    * ///////////// login to the server ///////// // login parts (within array $_POST): // // from - user logging in // // pwd - password // ///////////////////////////////////////////
    * @throws ChatException Thrown if method fails due to system-level error.    */
   public void logout(  )
      throws com.duroty.application.chat.exceptions.ChatException, java.rmi.RemoteException;

   /**
    * ///////////// login to the server ///////// // login parts (within array $_POST): // // from - user logging in // // pwd - password // ///////////////////////////////////////////
    * @throws ChatException Thrown if method fails due to system-level error.    */
   public void signout(  )
      throws com.duroty.application.chat.exceptions.ChatException, java.rmi.RemoteException;

   /**
    * ///////////// login to the server ///////// // login parts (within array $_POST): // // from - user logging in // // pwd - password // ///////////////////////////////////////////
    * @throws ChatException Thrown if method fails due to system-level error.    */
   public void setState( int state,java.lang.String message )
      throws com.duroty.application.chat.exceptions.ChatException, java.rmi.RemoteException;

}
