/*
 * Generated by XDoclet - Do not edit!
 */
package com.duroty.application.files.interfaces;

/**
 * Home interface for Files.
 * @xdoclet-generated at ${TODAY}
 * @copyright The XDoclet Team
 * @author XDoclet
 * @version ${version}
 */
public interface FilesHome
   extends javax.ejb.EJBHome
{
   public static final String COMP_NAME="duroty/ejb/Files";
   public static final String JNDI_NAME="duroty/ejb/Files";

   public com.duroty.application.files.interfaces.Files create()
      throws javax.ejb.CreateException,java.rmi.RemoteException;

}
