/*
 * Generated by XDoclet - Do not edit!
 */
package com.duroty.application.files.interfaces;

/**
 * Remote interface for FilesSearch.
 * @xdoclet-generated at ${TODAY}
 * @copyright The XDoclet Team
 * @author XDoclet
 * @version ${version}
 */
public interface FilesSearch
   extends javax.ejb.EJBObject
{
   /**
    * Search messages/attachments by text
    * @return SearchObj
    * @throws MailException Thrown if method fails due to system-level error.    */
   public com.duroty.application.files.utils.SearchObj simple( java.lang.String token,java.lang.String folderName,int label,int page,int messagesByPage,int order,java.lang.String orderType )
      throws com.duroty.application.mail.exceptions.MailException, java.rmi.RemoteException;

   /**
    * Search messages/attachments by text
    * @return SearchObj
    * @throws MailException Thrown if method fails due to system-level error.    */
   public com.duroty.application.files.utils.SearchObj advanced( com.duroty.application.mail.utils.AdvancedObj obj,int page,int messagesByPage,int order,java.lang.String orderType )
      throws com.duroty.application.mail.exceptions.MailException, java.rmi.RemoteException;

   /**
    * Did you mean
    * @return String
    * @throws MailException Thrown if method fails due to system-level error.    */
   public java.lang.String didYouMean( java.lang.String token )
      throws com.duroty.application.mail.exceptions.MailException, java.rmi.RemoteException;

}
