/*
 * Generated by XDoclet - Do not edit!
 */
package com.duroty.application.files.interfaces;

/**
 * Home interface for Store.
 * @xdoclet-generated at ${TODAY}
 * @copyright The XDoclet Team
 * @author XDoclet
 * @version ${version}
 */
public interface StoreHome
   extends javax.ejb.EJBHome
{
   public static final String COMP_NAME="duroty/ejb/Store";
   public static final String JNDI_NAME="duroty/ejb/Store";

   public com.duroty.application.files.interfaces.Store create()
      throws javax.ejb.CreateException,java.rmi.RemoteException;

}
