/*
* Copyright (C) 2006 Jordi Marquès Ferré
*
* This program is free software; you can redistribute it and/or modify
* it under the terms of the GNU General Public License as published by
* the Free Software Foundation; either version 2 of the License, or
* (at your option) any later version.
*
* This program is distributed in the hope that it will be useful,
* but WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
* GNU General Public License for more details.
*
* You should have received a copy of the GNU General Public License
* along with this software; see the file DUROTY.txt.
*
* Author: Jordi Marquès Ferré
* c/Mallorca 295 principal B 08037 Barcelona Spain
* Phone: +34 625397324
*/


/*
 * Generated by XDoclet - Do not edit!
 */
package com.duroty.application.mail.ejb;


/**
 * Session layer for Preferences.
 * @xdoclet-generated at ${TODAY}
 * @copyright The XDoclet Team
 * @author XDoclet
 * @version ${version}
 */
public class PreferencesSession
    extends com.duroty.application.mail.ejb.PreferencesBean
    implements javax.ejb.SessionBean {
    /**
          *
          */
    private static final long serialVersionUID = -4101258847524453764L;

    /**
     * DOCUMENT ME!
     *
     * @throws javax.ejb.EJBException DOCUMENT ME!
     * @throws java.rmi.RemoteException DOCUMENT ME!
     */
    public void ejbActivate()
        throws javax.ejb.EJBException, java.rmi.RemoteException {
        super.ejbActivate();
    }

    /**
     * DOCUMENT ME!
     *
     * @throws javax.ejb.EJBException DOCUMENT ME!
     * @throws java.rmi.RemoteException DOCUMENT ME!
     */
    public void ejbPassivate()
        throws javax.ejb.EJBException, java.rmi.RemoteException {
        super.ejbPassivate();
    }

    /**
     * DOCUMENT ME!
     *
     * @param ctx DOCUMENT ME!
     *
     * @throws javax.ejb.EJBException DOCUMENT ME!
     */
    public void setSessionContext(javax.ejb.SessionContext ctx)
        throws javax.ejb.EJBException {
        super.setSessionContext(ctx);
    }

    /**
     * DOCUMENT ME!
     */
    public void unsetSessionContext() {
    }

    /**
     * DOCUMENT ME!
     *
     * @throws javax.ejb.EJBException DOCUMENT ME!
     * @throws java.rmi.RemoteException DOCUMENT ME!
     */
    public void ejbRemove()
        throws javax.ejb.EJBException, java.rmi.RemoteException {
        super.ejbRemove();
    }
}
