/*
 * Generated by XDoclet - Do not edit!
 */
package com.duroty.application.open.interfaces;

/**
 * Home interface for Open.
 * @xdoclet-generated at ${TODAY}
 * @copyright The XDoclet Team
 * @author XDoclet
 * @version ${version}
 */
public interface OpenHome
   extends javax.ejb.EJBHome
{
   public static final String COMP_NAME="java:comp/env/ejb/Open";
   public static final String JNDI_NAME="duroty/ejb/Open";

   public com.duroty.application.open.interfaces.Open create()
      throws javax.ejb.CreateException,java.rmi.RemoteException;

}
