/*
 * Generated by XDoclet - Do not edit!
 */
package com.duroty.application.open.interfaces;

/**
 * Remote interface for Open.
 * @xdoclet-generated at ${TODAY}
 * @copyright The XDoclet Team
 * @author XDoclet
 * @version ${version}
 */
public interface Open
   extends javax.ejb.EJBObject
{
   /**
    * Forgot password
    * @throws MailException Thrown if method fails due to system-level error.    */
   public void forgotPassword( java.lang.String data )
      throws java.rmi.RemoteException;

   /**
    * Validate username
    * @throws MailException Thrown if method fails due to system-level error.    */
   public boolean existUser( java.lang.String username )
      throws java.rmi.RemoteException;

   /**
    * Register new user
    * @throws MailException Thrown if method fails due to system-level error.    */
   public void register( com.duroty.application.admin.utils.UserObj userObj )
      throws java.rmi.RemoteException;

}
