/*
 * Generated by XDoclet - Do not edit!
 */
package com.duroty.application.admin.interfaces;

/**
 * Home interface for Admin.
 * @xdoclet-generated at ${TODAY}
 * @copyright The XDoclet Team
 * @author XDoclet
 * @version ${version}
 */
public interface AdminHome
   extends javax.ejb.EJBHome
{
   public static final String COMP_NAME="duroty/ejb/Admin";
   public static final String JNDI_NAME="duroty/ejb/Admin";

   public com.duroty.application.admin.interfaces.Admin create()
      throws javax.ejb.CreateException,java.rmi.RemoteException;

}
