/*
 * Generated by XDoclet - Do not edit!
 */
package com.duroty.application.mail.interfaces;

/**
 * Home interface for Mail.
 * @xdoclet-generated at ${TODAY}
 * @copyright The XDoclet Team
 * @author XDoclet
 * @version ${version}
 */
public interface MailHome
   extends javax.ejb.EJBHome
{
   public static final String COMP_NAME="duroty/ejb/Mail";
   public static final String JNDI_NAME="duroty/ejb/Mail";

   public com.duroty.application.mail.interfaces.Mail create()
      throws javax.ejb.CreateException,java.rmi.RemoteException;

}
