/*
 * Generated by XDoclet - Do not edit!
 */
package com.duroty.application.mail.interfaces;

/**
 * Remote interface for Mail.
 * @xdoclet-generated at ${TODAY}
 * @copyright The XDoclet Team
 * @author XDoclet
 * @version ${version}
 */
public interface Mail
   extends javax.ejb.EJBObject
{
   /**
    * Get default folders
    * @throws MailException Thrown if method fails due to system-level error.    */
   public com.duroty.application.mail.utils.FolderObj[] getFolders(  )
      throws com.duroty.application.mail.exceptions.MailException, java.rmi.RemoteException;

   /**
    * Get user labels
    * @throws MailException Thrown if method fails due to system-level error.    */
   public java.util.Vector getLabels(  )
      throws com.duroty.application.mail.exceptions.MailException, java.rmi.RemoteException;

   /**
    * Get user lists contacts
    * @throws MailException Thrown if method fails due to system-level error.    */
   public java.util.Vector getContactList(  )
      throws com.duroty.application.mail.exceptions.MailException, java.rmi.RemoteException;

   /**
    * Posa amb estat d'arxivats un array de missatges
    * @throws MailException Thrown if method fails due to system-level error.    */
   public void archiveMessages( java.lang.String[] mids )
      throws com.duroty.application.mail.exceptions.MailException, java.rmi.RemoteException;

   /**
    * Borra els labels d'un conjunt de missatges
    * @throws MailException Thrown if method fails due to system-level error.    */
   public void deleteLabelsFromMessages( java.lang.String[] mids )
      throws com.duroty.application.mail.exceptions.MailException, java.rmi.RemoteException;

   /**
    * Borra els missatges d'un folder, en el cas que els missatges a borrar sigui TRASH o SPAM es borren definitivament
    * @throws MailException Thrown if method fails due to system-level error.    */
   public void deleteMessagesInFolder( java.lang.String folderName )
      throws com.duroty.application.mail.exceptions.MailException, java.rmi.RemoteException;

   /**
    * Borra els missatges d'un label, en el cas que els missatges a borrar sigui TRASH o SPAM es borren definitivament
    * @throws MailException Thrown if method fails due to system-level error.    */
   public void deleteMessagesInLabel( java.lang.Integer label )
      throws com.duroty.application.mail.exceptions.MailException, java.rmi.RemoteException;

   /**
    * Borra els missatges donats per mids en el cas que els missatges a borrar sigui TRASH o SPAM es borren definitivament
    * @throws MailException Thrown if method fails due to system-level error.    */
   public void deleteMessages( java.lang.String[] mids,java.lang.String folderName )
      throws com.duroty.application.mail.exceptions.MailException, java.rmi.RemoteException;

   /**
    * Recupera les propietats (capceleres) d'un missatge identificat per mid
    * @return String
    * @throws MailException Thrown if method fails due to system-level error.    */
   public java.lang.String displayProperties( java.lang.String mid )
      throws com.duroty.application.mail.exceptions.MailException, java.rmi.RemoteException;

   /**
    * Situa els missatges identificats per mids en un flag característic
    * @throws MailException Thrown if method fails due to system-level error.    */
   public void flagMessages( java.lang.String[] mids,java.lang.String flag )
      throws com.duroty.application.mail.exceptions.MailException, java.rmi.RemoteException;

   /**
    * Get messages by folder
    * @return Vector
    * @throws MailException Thrown if method fails due to system-level error.    */
   public java.util.Vector getMessages( java.lang.String folderName,int page,int messagesByPage,int order,java.lang.String orderType )
      throws com.duroty.application.mail.exceptions.MailException, java.rmi.RemoteException;

   /**
    * Get count messages in folder
    * @return Vector
    * @throws MailException Thrown if method fails due to system-level error.    */
   public int getCountMessages( java.lang.String folderName )
      throws com.duroty.application.mail.exceptions.MailException, java.rmi.RemoteException;

   /**
    * Get messages by label
    * @return Vector
    * @throws MailException Thrown if method fails due to system-level error.    */
   public java.util.Vector getMessages( int labIdint,int page,int messagesByPage,int order,java.lang.String orderType )
      throws com.duroty.application.mail.exceptions.MailException, java.rmi.RemoteException;

   /**
    * Get count messages in label
    * @return Vector
    * @throws MailException Thrown if method fails due to system-level error.    */
   public int getCountMessages( int labIdint )
      throws com.duroty.application.mail.exceptions.MailException, java.rmi.RemoteException;

   /**
    * Get message by id
    * @return MessageObj
    * @throws MailException Thrown if method fails due to system-level error.    */
   public com.duroty.application.mail.utils.MessageObj getMessage( java.lang.String mid,boolean readReferences,boolean isHtml,boolean displayImages )
      throws com.duroty.application.mail.exceptions.MailException, java.rmi.RemoteException;

   /**
    * Get attachment by mid and hash part
    * @return MailPartObj
    * @throws MailException Thrown if method fails due to system-level error.    */
   public com.duroty.application.mail.utils.MailPartObj getAttachment( java.lang.String mid,java.lang.String hash )
      throws com.duroty.application.mail.exceptions.MailException, java.rmi.RemoteException;

   /**
    * Get counter for info to boxes and labels
    * @return Counters
    * @throws MailException Thrown if method fails due to system-level error.    */
   public com.duroty.application.mail.utils.Counters getInfoCounters(  )
      throws com.duroty.application.mail.exceptions.MailException, java.rmi.RemoteException;

   /**
    * SPAM message by id
    * @throws MailException Thrown if method fails due to system-level error.    */
   public void spamMessage( java.lang.String[] mids )
      throws com.duroty.application.mail.exceptions.MailException, java.rmi.RemoteException;

   /**
    * NOT SPAM message by id
    * @throws MailException Thrown if method fails due to system-level error.    */
   public void notSpamMessage( java.lang.String[] mids )
      throws com.duroty.application.mail.exceptions.MailException, java.rmi.RemoteException;

   /**
    * Move messages to folder
    * @throws MailException Thrown if method fails due to system-level error.    */
   public void moveMessages( java.lang.String[] mids,java.lang.String folder )
      throws com.duroty.application.mail.exceptions.MailException, java.rmi.RemoteException;

   /**
    * Apply label to messages
    * @throws MailException Thrown if method fails due to system-level error.    */
   public void applyLabel( java.lang.Integer label,java.lang.String[] mids )
      throws com.duroty.application.mail.exceptions.MailException, java.rmi.RemoteException;

}
