/*
 * Generated by XDoclet - Do not edit!
 */
package com.duroty.application.mail.interfaces;

/**
 * Home interface for Search.
 * @xdoclet-generated at ${TODAY}
 * @copyright The XDoclet Team
 * @author XDoclet
 * @version ${version}
 */
public interface SearchHome
   extends javax.ejb.EJBHome
{
   public static final String COMP_NAME="duroty/ejb/Search";
   public static final String JNDI_NAME="duroty/ejb/Search";

   public com.duroty.application.mail.interfaces.Search create()
      throws javax.ejb.CreateException,java.rmi.RemoteException;

}
