/*
 * Generated by XDoclet - Do not edit!
 */
package com.duroty.application.mail.interfaces;


/**
 * Home interface for Send.
 * @xdoclet-generated at ${TODAY}
 * @copyright The XDoclet Team
 * @author XDoclet
 * @version ${version}
 */
public interface SendHome extends javax.ejb.EJBHome {
    /**
     * DOCUMENT ME!
     */
    public static final String COMP_NAME = "duroty/ejb/Send";

    /**
     * DOCUMENT ME!
     */
    public static final String JNDI_NAME = "duroty/ejb/Send";

    /**
     * DOCUMENT ME!
     *
     * @return DOCUMENT ME!
     *
     * @throws javax.ejb.CreateException DOCUMENT ME!
     * @throws java.rmi.RemoteException DOCUMENT ME!
     */
    public com.duroty.application.mail.interfaces.Send create()
        throws javax.ejb.CreateException, java.rmi.RemoteException;
}
