package com.duroty.hibernate;


// Generated 09-oct-2006 9:59:12 by Hibernate Tools 3.1.0.beta5

/**
 * Alias generated by hbm2java
 */
public class Alias implements java.io.Serializable {
    // Fields    

    /**
     *
     */
    private static final long serialVersionUID = 6238564525541173071L;

    /**
     * DOCUMENT ME!
     */
    private int aliIdint;

    /**
     * DOCUMENT ME!
     */
    private Users users;

    /**
     * DOCUMENT ME!
     */
    private String aliName;

    // Constructors

    /** default constructor */
    public Alias() {
    }

    /** full constructor */
    public Alias(int aliIdint, Users users, String aliName) {
        this.aliIdint = aliIdint;
        this.users = users;
        this.aliName = aliName;
    }

    // Property accessors
    public int getAliIdint() {
        return this.aliIdint;
    }

    /**
     * DOCUMENT ME!
     *
     * @param aliIdint DOCUMENT ME!
     */
    public void setAliIdint(int aliIdint) {
        this.aliIdint = aliIdint;
    }

    /**
     * DOCUMENT ME!
     *
     * @return DOCUMENT ME!
     */
    public Users getUsers() {
        return this.users;
    }

    /**
     * DOCUMENT ME!
     *
     * @param users DOCUMENT ME!
     */
    public void setUsers(Users users) {
        this.users = users;
    }

    /**
     * DOCUMENT ME!
     *
     * @return DOCUMENT ME!
     */
    public String getAliName() {
        return this.aliName;
    }

    /**
     * DOCUMENT ME!
     *
     * @param aliName DOCUMENT ME!
     */
    public void setAliName(String aliName) {
        this.aliName = aliName;
    }
}
