/*
* Copyright (C) 2006 Jordi Marquès Ferré
*
* This program is free software; you can redistribute it and/or modify
* it under the terms of the GNU General Public License as published by
* the Free Software Foundation; either version 2 of the License, or
* (at your option) any later version.
*
* This program is distributed in the hope that it will be useful,
* but WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
* GNU General Public License for more details.
*
* You should have received a copy of the GNU General Public License
* along with this software; see the file DUROTY.txt.
*
* Author: Jordi Marquès Ferré
* c/Mallorca 295 principal B 08037 Barcelona Spain
* Phone: +34 625397324
*/


package com.duroty.hibernate;

import java.util.Date;


// Generated 02-oct-2006 10:24:25 by Hibernate Tools 3.1.0.beta5

/**
 * BuddyList generated by hbm2java
 */
public class BuddyList implements java.io.Serializable {
    /**
         *
         */
    private static final long serialVersionUID = -1178807366476301559L;

    /**
    * DOCUMENT ME!
    */
    private int buliIdint;

    /**
     * DOCUMENT ME!
     */
    private Users usersByBuliOwnerIdint;

    /**
     * DOCUMENT ME!
     */
    private Users usersByBuliBuddyIdint;

    /**
     * DOCUMENT ME!
     */
    private boolean buliActive;

    /**
     * DOCUMENT ME!
     */
    private Date buliLastDate;

    // Constructors

    /** default constructor */
    public BuddyList() {
    }

    /** full constructor */
    public BuddyList(int buliIdint, Users usersByBuliOwnerIdint,
        Users usersByBuliBuddyIdint, boolean buliActive, Date buliLastDate) {
        this.buliIdint = buliIdint;
        this.usersByBuliOwnerIdint = usersByBuliOwnerIdint;
        this.usersByBuliBuddyIdint = usersByBuliBuddyIdint;
        this.buliActive = buliActive;
        this.buliLastDate = buliLastDate;
    }

    // Property accessors
    public int getBuliIdint() {
        return this.buliIdint;
    }

    /**
     * DOCUMENT ME!
     *
     * @param buliIdint DOCUMENT ME!
     */
    public void setBuliIdint(int buliIdint) {
        this.buliIdint = buliIdint;
    }

    /**
     * DOCUMENT ME!
     *
     * @return DOCUMENT ME!
     */
    public Users getUsersByBuliOwnerIdint() {
        return this.usersByBuliOwnerIdint;
    }

    /**
     * DOCUMENT ME!
     *
     * @param usersByBuliOwnerIdint DOCUMENT ME!
     */
    public void setUsersByBuliOwnerIdint(Users usersByBuliOwnerIdint) {
        this.usersByBuliOwnerIdint = usersByBuliOwnerIdint;
    }

    /**
     * DOCUMENT ME!
     *
     * @return DOCUMENT ME!
     */
    public Users getUsersByBuliBuddyIdint() {
        return this.usersByBuliBuddyIdint;
    }

    /**
     * DOCUMENT ME!
     *
     * @param usersByBuliBuddyIdint DOCUMENT ME!
     */
    public void setUsersByBuliBuddyIdint(Users usersByBuliBuddyIdint) {
        this.usersByBuliBuddyIdint = usersByBuliBuddyIdint;
    }

    /**
     * DOCUMENT ME!
     *
     * @return DOCUMENT ME!
     */
    public boolean isBuliActive() {
        return this.buliActive;
    }

    /**
     * DOCUMENT ME!
     *
     * @param buliActive DOCUMENT ME!
     */
    public void setBuliActive(boolean buliActive) {
        this.buliActive = buliActive;
    }

    /**
     * DOCUMENT ME!
     *
     * @return DOCUMENT ME!
     */
    public Date getBuliLastDate() {
        return this.buliLastDate;
    }

    /**
     * DOCUMENT ME!
     *
     * @param buliLastDate DOCUMENT ME!
     */
    public void setBuliLastDate(Date buliLastDate) {
        this.buliLastDate = buliLastDate;
    }
}
