/*
* Copyright (C) 2006 Jordi Marquès Ferré
*
* This program is free software; you can redistribute it and/or modify
* it under the terms of the GNU General Public License as published by
* the Free Software Foundation; either version 2 of the License, or
* (at your option) any later version.
*
* This program is distributed in the hope that it will be useful,
* but WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
* GNU General Public License for more details.
*
* You should have received a copy of the GNU General Public License
* along with this software; see the file DUROTY.txt.
*
* Author: Jordi Marquès Ferré
* c/Mallorca 295 principal B 08037 Barcelona Spain
* Phone: +34 625397324
*/


package com.duroty.hibernate;

import java.util.Date;


// Generated 02-oct-2006 10:24:25 by Hibernate Tools 3.1.0.beta5

/**
 * Conversations generated by hbm2java
 */
public class Conversations implements java.io.Serializable {
    /**
         *
         */
    private static final long serialVersionUID = -354620301415750204L;

    // Fields    

    /**
     * DOCUMENT ME!
     */
    private int convIdint;

    /**
     * DOCUMENT ME!
     */
    private Users usersByConvSenderIdint;

    /**
     * DOCUMENT ME!
     */
    private Users usersByConvRecipientIdint;

    /**
     * DOCUMENT ME!
     */
    private String convMessage;

    /**
     * DOCUMENT ME!
     */
    private Date convStamp;

    // Constructors

    /** default constructor */
    public Conversations() {
    }

    /** full constructor */
    public Conversations(int convIdint, Users usersByConvSenderIdint,
        Users usersByConvRecipientIdint, String convMessage, Date convStamp) {
        this.convIdint = convIdint;
        this.usersByConvSenderIdint = usersByConvSenderIdint;
        this.usersByConvRecipientIdint = usersByConvRecipientIdint;
        this.convMessage = convMessage;
        this.convStamp = convStamp;
    }

    // Property accessors
    public int getConvIdint() {
        return this.convIdint;
    }

    /**
     * DOCUMENT ME!
     *
     * @param convIdint DOCUMENT ME!
     */
    public void setConvIdint(int convIdint) {
        this.convIdint = convIdint;
    }

    /**
     * DOCUMENT ME!
     *
     * @return DOCUMENT ME!
     */
    public Users getUsersByConvSenderIdint() {
        return this.usersByConvSenderIdint;
    }

    /**
     * DOCUMENT ME!
     *
     * @param usersByConvSenderIdint DOCUMENT ME!
     */
    public void setUsersByConvSenderIdint(Users usersByConvSenderIdint) {
        this.usersByConvSenderIdint = usersByConvSenderIdint;
    }

    /**
     * DOCUMENT ME!
     *
     * @return DOCUMENT ME!
     */
    public Users getUsersByConvRecipientIdint() {
        return this.usersByConvRecipientIdint;
    }

    /**
     * DOCUMENT ME!
     *
     * @param usersByConvRecipientIdint DOCUMENT ME!
     */
    public void setUsersByConvRecipientIdint(Users usersByConvRecipientIdint) {
        this.usersByConvRecipientIdint = usersByConvRecipientIdint;
    }

    /**
     * DOCUMENT ME!
     *
     * @return DOCUMENT ME!
     */
    public String getConvMessage() {
        return this.convMessage;
    }

    /**
     * DOCUMENT ME!
     *
     * @param convMessage DOCUMENT ME!
     */
    public void setConvMessage(String convMessage) {
        this.convMessage = convMessage;
    }

    /**
     * DOCUMENT ME!
     *
     * @return DOCUMENT ME!
     */
    public Date getConvStamp() {
        return this.convStamp;
    }

    /**
     * DOCUMENT ME!
     *
     * @param convStamp DOCUMENT ME!
     */
    public void setConvStamp(Date convStamp) {
        this.convStamp = convStamp;
    }
}
