/*
* Copyright (C) 2006 Jordi Marquès Ferré
*
* This program is free software; you can redistribute it and/or modify
* it under the terms of the GNU General Public License as published by
* the Free Software Foundation; either version 2 of the License, or
* (at your option) any later version.
*
* This program is distributed in the hope that it will be useful,
* but WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
* GNU General Public License for more details.
*
* You should have received a copy of the GNU General Public License
* along with this software; see the file DUROTY.txt.
*
* Author: Jordi Marquès Ferré
* c/Mallorca 295 principal B 08037 Barcelona Spain
* Phone: +34 625397324
*/


package com.duroty.hibernate;


// Generated 31-jul-2006 11:12:15 by Hibernate Tools 3.1.0.beta5

/**
 * Identity generated by hbm2java
 */
public class Identity implements java.io.Serializable {
    // Fields    

    /**
     *
     */
    private static final long serialVersionUID = -5225561710292770945L;

    /**
     * DOCUMENT ME!
     */
    private int ideIdint;

    /**
     * DOCUMENT ME!
     */
    private Users users;

    /**
     * DOCUMENT ME!
     */
    private String ideName;

    /**
     * DOCUMENT ME!
     */
    private String ideEmail;

    /**
     * DOCUMENT ME!
     */
    private String ideReplyTo;

    /**
     * DOCUMENT ME!
     */
    private String ideCode;

    /**
     * DOCUMENT ME!
     */
    private boolean ideActive;

    /**
     * DOCUMENT ME!
     */
    private boolean ideDefault;

    // Constructors

    /** default constructor */
    public Identity() {
    }

    /** minimal constructor */
    public Identity(int ideIdint, Users users, String ideEmail,
        String ideReplyTo, String ideCode, boolean ideActive, boolean ideDefault) {
        this.ideIdint = ideIdint;
        this.users = users;
        this.ideEmail = ideEmail;
        this.ideReplyTo = ideReplyTo;
        this.ideCode = ideCode;
        this.ideActive = ideActive;
        this.ideDefault = ideDefault;
    }

    /** full constructor */
    public Identity(int ideIdint, Users users, String ideName, String ideEmail,
        String ideReplyTo, String ideCode, boolean ideActive, boolean ideDefault) {
        this.ideIdint = ideIdint;
        this.users = users;
        this.ideName = ideName;
        this.ideEmail = ideEmail;
        this.ideReplyTo = ideReplyTo;
        this.ideCode = ideCode;
        this.ideActive = ideActive;
        this.ideDefault = ideDefault;
    }

    // Property accessors

    /**
     * DOCUMENT ME!
     *
     * @return DOCUMENT ME!
     */
    public int getIdeIdint() {
        return this.ideIdint;
    }

    /**
     * DOCUMENT ME!
     *
     * @param ideIdint DOCUMENT ME!
     */
    public void setIdeIdint(int ideIdint) {
        this.ideIdint = ideIdint;
    }

    /**
     * DOCUMENT ME!
     *
     * @return DOCUMENT ME!
     */
    public Users getUsers() {
        return this.users;
    }

    /**
     * DOCUMENT ME!
     *
     * @param users DOCUMENT ME!
     */
    public void setUsers(Users users) {
        this.users = users;
    }

    /**
     * DOCUMENT ME!
     *
     * @return DOCUMENT ME!
     */
    public String getIdeName() {
        return this.ideName;
    }

    /**
     * DOCUMENT ME!
     *
     * @param ideName DOCUMENT ME!
     */
    public void setIdeName(String ideName) {
        this.ideName = ideName;
    }

    /**
     * DOCUMENT ME!
     *
     * @return DOCUMENT ME!
     */
    public String getIdeEmail() {
        return this.ideEmail;
    }

    /**
     * DOCUMENT ME!
     *
     * @param ideEmail DOCUMENT ME!
     */
    public void setIdeEmail(String ideEmail) {
        this.ideEmail = ideEmail;
    }

    /**
     * DOCUMENT ME!
     *
     * @return DOCUMENT ME!
     */
    public String getIdeReplyTo() {
        return this.ideReplyTo;
    }

    /**
     * DOCUMENT ME!
     *
     * @param ideReplyTo DOCUMENT ME!
     */
    public void setIdeReplyTo(String ideReplyTo) {
        this.ideReplyTo = ideReplyTo;
    }

    /**
     * DOCUMENT ME!
     *
     * @return DOCUMENT ME!
     */
    public String getIdeCode() {
        return this.ideCode;
    }

    /**
     * DOCUMENT ME!
     *
     * @param ideCode DOCUMENT ME!
     */
    public void setIdeCode(String ideCode) {
        this.ideCode = ideCode;
    }

    /**
     * DOCUMENT ME!
     *
     * @return DOCUMENT ME!
     */
    public boolean isIdeActive() {
        return this.ideActive;
    }

    /**
     * DOCUMENT ME!
     *
     * @param ideActive DOCUMENT ME!
     */
    public void setIdeActive(boolean ideActive) {
        this.ideActive = ideActive;
    }

    /**
     * DOCUMENT ME!
     *
     * @return DOCUMENT ME!
     */
    public boolean isIdeDefault() {
        return this.ideDefault;
    }

    /**
     * DOCUMENT ME!
     *
     * @param ideDefault DOCUMENT ME!
     */
    public void setIdeDefault(boolean ideDefault) {
        this.ideDefault = ideDefault;
    }
}
