/*
* Copyright (C) 2006 Jordi Marquès Ferré
*
* This program is free software; you can redistribute it and/or modify
* it under the terms of the GNU General Public License as published by
* the Free Software Foundation; either version 2 of the License, or
* (at your option) any later version.
*
* This program is distributed in the hope that it will be useful,
* but WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
* GNU General Public License for more details.
*
* You should have received a copy of the GNU General Public License
* along with this software; see the file DUROTY.txt.
*
* Author: Jordi Marquès Ferré
* c/Mallorca 295 principal B 08037 Barcelona Spain
* Phone: +34 625397324
*/


package com.duroty.hibernate;


// Generated 02-ago-2006 17:07:31 by Hibernate Tools 3.1.0.beta5
import java.util.HashSet;
import java.util.Set;


/**
 * Label generated by hbm2java
 */
public class Label implements java.io.Serializable {
    // Fields    

    /**
     *
     */
    private static final long serialVersionUID = -2252021254130470453L;

    /**
     * DOCUMENT ME!
     */
    private int labIdint;

    /**
     * DOCUMENT ME!
     */
    private Users users;

    /**
     * DOCUMENT ME!
     */
    private String labName;

    /**
     * DOCUMENT ME!
     */
    private Set labMeses = new HashSet(0);

    /**
     * DOCUMENT ME!
     */
    private Set filters = new HashSet(0);

    // Constructors

    /** default constructor */
    public Label() {
    }

    /** minimal constructor */
    public Label(int labIdint, Users users, String labName) {
        this.labIdint = labIdint;
        this.users = users;
        this.labName = labName;
    }

    /** full constructor */
    public Label(int labIdint, Users users, String labName, Set labMeses,
        Set filters) {
        this.labIdint = labIdint;
        this.users = users;
        this.labName = labName;
        this.labMeses = labMeses;
        this.filters = filters;
    }

    // Property accessors
    public int getLabIdint() {
        return this.labIdint;
    }

    /**
     * DOCUMENT ME!
     *
     * @param labIdint DOCUMENT ME!
     */
    public void setLabIdint(int labIdint) {
        this.labIdint = labIdint;
    }

    /**
     * DOCUMENT ME!
     *
     * @return DOCUMENT ME!
     */
    public Users getUsers() {
        return this.users;
    }

    /**
     * DOCUMENT ME!
     *
     * @param users DOCUMENT ME!
     */
    public void setUsers(Users users) {
        this.users = users;
    }

    /**
     * DOCUMENT ME!
     *
     * @return DOCUMENT ME!
     */
    public String getLabName() {
        return this.labName;
    }

    /**
     * DOCUMENT ME!
     *
     * @param labName DOCUMENT ME!
     */
    public void setLabName(String labName) {
        this.labName = labName;
    }

    /**
     * DOCUMENT ME!
     *
     * @return DOCUMENT ME!
     */
    public Set getLabMeses() {
        return this.labMeses;
    }

    /**
     * DOCUMENT ME!
     *
     * @param labMeses DOCUMENT ME!
     */
    public void setLabMeses(Set labMeses) {
        this.labMeses = labMeses;
    }

    /**
     * DOCUMENT ME!
     *
     * @return DOCUMENT ME!
     */
    public Set getFilters() {
        return this.filters;
    }

    /**
     * DOCUMENT ME!
     *
     * @param filters DOCUMENT ME!
     */
    public void setFilters(Set filters) {
        this.filters = filters;
    }
}
