package com.duroty.hibernate;


// Generated 31-jul-2006 11:12:15 by Hibernate Tools 3.1.0.beta5

/**
 * UserRole generated by hbm2java
 */
public class UserRole implements java.io.Serializable {
    // Fields    

    /**
     *
     */
    private static final long serialVersionUID = -4346115411235345377L;

    /**
     * DOCUMENT ME!
     */
    private UserRoleId id;

    // Constructors

    /** default constructor */
    public UserRole() {
    }

    /** full constructor */
    public UserRole(UserRoleId id) {
        this.id = id;
    }

    // Property accessors
    /**
     * DOCUMENT ME!
     *
     * @return DOCUMENT ME!
     */
    public UserRoleId getId() {
        return this.id;
    }

    /**
     * DOCUMENT ME!
     *
     * @param id DOCUMENT ME!
     */
    public void setId(UserRoleId id) {
        this.id = id;
    }
}
