/*
* Copyright (C) 2006 Jordi Marquès Ferré
*
* This program is free software; you can redistribute it and/or modify
* it under the terms of the GNU General Public License as published by
* the Free Software Foundation; either version 2 of the License, or
* (at your option) any later version.
*
* This program is distributed in the hope that it will be useful,
* but WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
* GNU General Public License for more details.
*
* You should have received a copy of the GNU General Public License
* along with this software; see the file DUROTY.txt.
*
* Author: Jordi Marquès Ferré
* c/Mallorca 295 principal B 08037 Barcelona Spain
* Phone: +34 625397324
*/


package com.duroty.hibernate;


// Generated 31-jul-2006 11:12:15 by Hibernate Tools 3.1.0.beta5
import java.util.Date;
import java.util.HashSet;
import java.util.Set;


/**
 * Users generated by hbm2java
 */
public class Users implements java.io.Serializable {
    //	 Fields    

    /**
     *
     */
    private static final long serialVersionUID = -1078511370612342550L;

    /**
     * DOCUMENT ME!
     */
    private int useIdint;

    /**
     * DOCUMENT ME!
     */
    private String useUsername;

    /**
     * DOCUMENT ME!
     */
    private String usePassword;

    /**
     * DOCUMENT ME!
     */
    private boolean useActive;

    /**
     * DOCUMENT ME!
     */
    private Date useRegisterDate;

    /**
     * DOCUMENT ME!
     */
    private String useEmail;

    /**
     * DOCUMENT ME!
     */
    private String useLanguage;

    /**
     * DOCUMENT ME!
     */
    private int useIsOnline;

    /**
     * DOCUMENT ME!
     */
    private Date useLastPing;

    /**
     * DOCUMENT ME!
     */
    private int useLastState;

    /**
     * DOCUMENT ME!
     */
    private String useCustomMessage;

    /**
     * DOCUMENT ME!
     */
    private String useName;

    /**
     * DOCUMENT ME!
     */
    private Set identities = new HashSet(0);

    /**
     * DOCUMENT ME!
     */
    private Set messages = new HashSet(0);

    /**
     * DOCUMENT ME!
     */
    private Set conversationsesForConvSenderIdint = new HashSet(0);

    /**
     * DOCUMENT ME!
     */
    private Set buddyListsForBuliOwnerIdint = new HashSet(0);

    /**
     * DOCUMENT ME!
     */
    private Set conversationsesForConvRecipientIdint = new HashSet(0);

    /**
     * DOCUMENT ME!
     */
    private Set feedChannels = new HashSet(0);

    /**
     * DOCUMENT ME!
     */
    private Set bookmarks = new HashSet(0);

    /**
     * DOCUMENT ME!
     */
    private Set labels = new HashSet(0);

    /**
     * DOCUMENT ME!
     */
    private Set mailPreferenceses = new HashSet(0);

    /**
     * DOCUMENT ME!
     */
    private Set contacts = new HashSet(0);

    /**
     * DOCUMENT ME!
     */
    private Set buddyListsForBuliBuddyIdint = new HashSet(0);

    /**
     * DOCUMENT ME!
     */
    private Set userRoles = new HashSet(0);

    /**
     * DOCUMENT ME!
     */
    private Set contactLists = new HashSet(0);

    // Constructors

    /** default constructor */
    public Users() {
    }

    /** minimal constructor */
    public Users(int useIdint, String useUsername, String usePassword,
        boolean useActive, Date useRegisterDate, String useEmail,
        String useLanguage) {
        this.useIdint = useIdint;
        this.useUsername = useUsername;
        this.usePassword = usePassword;
        this.useActive = useActive;
        this.useRegisterDate = useRegisterDate;
        this.useEmail = useEmail;
        this.useLanguage = useLanguage;
    }

    /** full constructor */
    public Users(int useIdint, String useUsername, String usePassword,
        boolean useActive, Date useRegisterDate, String useEmail,
        String useLanguage, int useIsOnline, Date useLastPing,
        int useLastState, String useCustomMessage, String useName,
        Set identities, Set messages, Set conversationsesForConvSenderIdint,
        Set buddyListsForBuliOwnerIdint,
        Set conversationsesForConvRecipientIdint, Set feedChannels,
        Set bookmarks, Set labels, Set mailPreferenceses, Set contacts,
        Set buddyListsForBuliBuddyIdint, Set userRoles, Set contactLists) {
        this.useIdint = useIdint;
        this.useUsername = useUsername;
        this.usePassword = usePassword;
        this.useActive = useActive;
        this.useRegisterDate = useRegisterDate;
        this.useEmail = useEmail;
        this.useLanguage = useLanguage;
        this.useIsOnline = useIsOnline;
        this.useLastPing = useLastPing;
        this.useLastState = useLastState;
        this.useCustomMessage = useCustomMessage;
        this.useName = useName;
        this.identities = identities;
        this.messages = messages;
        this.conversationsesForConvSenderIdint = conversationsesForConvSenderIdint;
        this.buddyListsForBuliOwnerIdint = buddyListsForBuliOwnerIdint;
        this.conversationsesForConvRecipientIdint = conversationsesForConvRecipientIdint;
        this.feedChannels = feedChannels;
        this.bookmarks = bookmarks;
        this.labels = labels;
        this.mailPreferenceses = mailPreferenceses;
        this.contacts = contacts;
        this.buddyListsForBuliBuddyIdint = buddyListsForBuliBuddyIdint;
        this.userRoles = userRoles;
        this.contactLists = contactLists;
    }

    // Property accessors
    public int getUseIdint() {
        return this.useIdint;
    }

    /**
     * DOCUMENT ME!
     *
     * @param useIdint DOCUMENT ME!
     */
    public void setUseIdint(int useIdint) {
        this.useIdint = useIdint;
    }

    /**
     * DOCUMENT ME!
     *
     * @return DOCUMENT ME!
     */
    public String getUseUsername() {
        return this.useUsername;
    }

    /**
     * DOCUMENT ME!
     *
     * @param useUsername DOCUMENT ME!
     */
    public void setUseUsername(String useUsername) {
        this.useUsername = useUsername;
    }

    /**
     * DOCUMENT ME!
     *
     * @return DOCUMENT ME!
     */
    public String getUsePassword() {
        return this.usePassword;
    }

    /**
     * DOCUMENT ME!
     *
     * @param usePassword DOCUMENT ME!
     */
    public void setUsePassword(String usePassword) {
        this.usePassword = usePassword;
    }

    /**
     * DOCUMENT ME!
     *
     * @return DOCUMENT ME!
     */
    public boolean isUseActive() {
        return this.useActive;
    }

    /**
     * DOCUMENT ME!
     *
     * @param useActive DOCUMENT ME!
     */
    public void setUseActive(boolean useActive) {
        this.useActive = useActive;
    }

    /**
     * DOCUMENT ME!
     *
     * @return DOCUMENT ME!
     */
    public Date getUseRegisterDate() {
        return this.useRegisterDate;
    }

    /**
     * DOCUMENT ME!
     *
     * @param useRegisterDate DOCUMENT ME!
     */
    public void setUseRegisterDate(Date useRegisterDate) {
        this.useRegisterDate = useRegisterDate;
    }

    /**
     * DOCUMENT ME!
     *
     * @return DOCUMENT ME!
     */
    public String getUseEmail() {
        return this.useEmail;
    }

    /**
     * DOCUMENT ME!
     *
     * @param useEmail DOCUMENT ME!
     */
    public void setUseEmail(String useEmail) {
        this.useEmail = useEmail;
    }

    /**
     * DOCUMENT ME!
     *
     * @return DOCUMENT ME!
     */
    public String getUseLanguage() {
        return this.useLanguage;
    }

    /**
     * DOCUMENT ME!
     *
     * @param useLanguage DOCUMENT ME!
     */
    public void setUseLanguage(String useLanguage) {
        this.useLanguage = useLanguage;
    }

    /**
     * DOCUMENT ME!
     *
     * @return DOCUMENT ME!
     */
    public int getUseIsOnline() {
        return this.useIsOnline;
    }

    /**
     * DOCUMENT ME!
     *
     * @param useIsOnline DOCUMENT ME!
     */
    public void setUseIsOnline(int useIsOnline) {
        this.useIsOnline = useIsOnline;
    }

    /**
     * DOCUMENT ME!
     *
     * @return DOCUMENT ME!
     */
    public Date getUseLastPing() {
        return this.useLastPing;
    }

    /**
     * DOCUMENT ME!
     *
     * @param useLastPing DOCUMENT ME!
     */
    public void setUseLastPing(Date useLastPing) {
        this.useLastPing = useLastPing;
    }

    /**
     * DOCUMENT ME!
     *
     * @return DOCUMENT ME!
     */
    public int getUseLastState() {
        return this.useLastState;
    }

    /**
     * DOCUMENT ME!
     *
     * @param useLastState DOCUMENT ME!
     */
    public void setUseLastState(int useLastState) {
        this.useLastState = useLastState;
    }

    /**
     * DOCUMENT ME!
     *
     * @return DOCUMENT ME!
     */
    public String getUseCustomMessage() {
        return this.useCustomMessage;
    }

    /**
     * DOCUMENT ME!
     *
     * @param useCustomMessage DOCUMENT ME!
     */
    public void setUseCustomMessage(String useCustomMessage) {
        this.useCustomMessage = useCustomMessage;
    }

    /**
     * DOCUMENT ME!
     *
     * @return DOCUMENT ME!
     */
    public String getUseName() {
        return this.useName;
    }

    /**
     * DOCUMENT ME!
     *
     * @param useName DOCUMENT ME!
     */
    public void setUseName(String useName) {
        this.useName = useName;
    }

    /**
     * DOCUMENT ME!
     *
     * @return DOCUMENT ME!
     */
    public Set getIdentities() {
        return this.identities;
    }

    /**
     * DOCUMENT ME!
     *
     * @param identities DOCUMENT ME!
     */
    public void setIdentities(Set identities) {
        this.identities = identities;
    }

    /**
     * DOCUMENT ME!
     *
     * @return DOCUMENT ME!
     */
    public Set getMessages() {
        return this.messages;
    }

    /**
     * DOCUMENT ME!
     *
     * @param messages DOCUMENT ME!
     */
    public void setMessages(Set messages) {
        this.messages = messages;
    }

    /**
     * DOCUMENT ME!
     *
     * @return DOCUMENT ME!
     */
    public Set getConversationsesForConvSenderIdint() {
        return this.conversationsesForConvSenderIdint;
    }

    /**
     * DOCUMENT ME!
     *
     * @param conversationsesForConvSenderIdint DOCUMENT ME!
     */
    public void setConversationsesForConvSenderIdint(
        Set conversationsesForConvSenderIdint) {
        this.conversationsesForConvSenderIdint = conversationsesForConvSenderIdint;
    }

    /**
     * DOCUMENT ME!
     *
     * @return DOCUMENT ME!
     */
    public Set getBuddyListsForBuliOwnerIdint() {
        return this.buddyListsForBuliOwnerIdint;
    }

    /**
     * DOCUMENT ME!
     *
     * @param buddyListsForBuliOwnerIdint DOCUMENT ME!
     */
    public void setBuddyListsForBuliOwnerIdint(Set buddyListsForBuliOwnerIdint) {
        this.buddyListsForBuliOwnerIdint = buddyListsForBuliOwnerIdint;
    }

    /**
     * DOCUMENT ME!
     *
     * @return DOCUMENT ME!
     */
    public Set getConversationsesForConvRecipientIdint() {
        return this.conversationsesForConvRecipientIdint;
    }

    /**
     * DOCUMENT ME!
     *
     * @param conversationsesForConvRecipientIdint DOCUMENT ME!
     */
    public void setConversationsesForConvRecipientIdint(
        Set conversationsesForConvRecipientIdint) {
        this.conversationsesForConvRecipientIdint = conversationsesForConvRecipientIdint;
    }

    /**
     * DOCUMENT ME!
     *
     * @return DOCUMENT ME!
     */
    public Set getFeedChannels() {
        return this.feedChannels;
    }

    /**
     * DOCUMENT ME!
     *
     * @param feedChannels DOCUMENT ME!
     */
    public void setFeedChannels(Set feedChannels) {
        this.feedChannels = feedChannels;
    }

    /**
     * DOCUMENT ME!
     *
     * @return DOCUMENT ME!
     */
    public Set getBookmarks() {
        return this.bookmarks;
    }

    /**
     * DOCUMENT ME!
     *
     * @param bookmarks DOCUMENT ME!
     */
    public void setBookmarks(Set bookmarks) {
        this.bookmarks = bookmarks;
    }

    /**
     * DOCUMENT ME!
     *
     * @return DOCUMENT ME!
     */
    public Set getLabels() {
        return this.labels;
    }

    /**
     * DOCUMENT ME!
     *
     * @param labels DOCUMENT ME!
     */
    public void setLabels(Set labels) {
        this.labels = labels;
    }

    /**
     * DOCUMENT ME!
     *
     * @return DOCUMENT ME!
     */
    public Set getMailPreferenceses() {
        return this.mailPreferenceses;
    }

    /**
     * DOCUMENT ME!
     *
     * @param mailPreferenceses DOCUMENT ME!
     */
    public void setMailPreferenceses(Set mailPreferenceses) {
        this.mailPreferenceses = mailPreferenceses;
    }

    /**
     * DOCUMENT ME!
     *
     * @return DOCUMENT ME!
     */
    public Set getContacts() {
        return this.contacts;
    }

    /**
     * DOCUMENT ME!
     *
     * @param contacts DOCUMENT ME!
     */
    public void setContacts(Set contacts) {
        this.contacts = contacts;
    }

    /**
     * DOCUMENT ME!
     *
     * @return DOCUMENT ME!
     */
    public Set getBuddyListsForBuliBuddyIdint() {
        return this.buddyListsForBuliBuddyIdint;
    }

    /**
     * DOCUMENT ME!
     *
     * @param buddyListsForBuliBuddyIdint DOCUMENT ME!
     */
    public void setBuddyListsForBuliBuddyIdint(Set buddyListsForBuliBuddyIdint) {
        this.buddyListsForBuliBuddyIdint = buddyListsForBuliBuddyIdint;
    }

    /**
     * DOCUMENT ME!
     *
     * @return DOCUMENT ME!
     */
    public Set getUserRoles() {
        return this.userRoles;
    }

    /**
     * DOCUMENT ME!
     *
     * @param userRoles DOCUMENT ME!
     */
    public void setUserRoles(Set userRoles) {
        this.userRoles = userRoles;
    }

    /**
     * DOCUMENT ME!
     *
     * @param userRole DOCUMENT ME!
     */
    public void addUserRole(UserRole userRole) {
        this.userRoles.add(userRole);
    }

    /**
     * DOCUMENT ME!
     *
     * @return DOCUMENT ME!
     */
    public Set getContactLists() {
        return this.contactLists;
    }

    /**
     * DOCUMENT ME!
     *
     * @param contactLists DOCUMENT ME!
     */
    public void setContactLists(Set contactLists) {
        this.contactLists = contactLists;
    }

    /**
     * DOCUMENT ME!
     *
     * @param identity DOCUMENT ME!
     */
    public void addIdentity(Identity identity) {
        this.identities.add(identity);
    }
}
