/*
 * Generated by XDoclet - Do not edit!
 */
package com.duroty.application.files.interfaces;

/**
 * Remote interface for Store.
 * @xdoclet-generated at ${TODAY}
 * @copyright The XDoclet Team
 * @author XDoclet
 * @version ${version}
 */
public interface Store
   extends javax.ejb.EJBObject
{
   /**
    * An example business method
    * @throws EJBException Thrown if method fails due to system-level error.    */
   public void send( java.util.Vector files,int label,java.lang.String charset )
      throws com.duroty.application.files.exceptions.FilesException, java.rmi.RemoteException;

}
